### ISSUE TITLE
0.1.6 release?

### ISSUE THREAD

**Issue by landroni** [skranz/restorepoint#1]
There have been several bug fixes looking at the logs, and IMO the `break.point()` function can be particularly useful in certain circumstances. 

Are there any plans for a new 0.1.6 release?

**Comment by skranz** [comment]
Probably it was indeed time for a new release. I updated the version to 0.1.7 and also put this new version on CRAN. (just forgot to update the news file....)

**Comment by landroni** [comment]
Nice, thanks!

**Comment by landroni** [comment]
As for the NEWS file, maybe it's worth updating it here on GIT; this way people looking for the logs can find the info on the changes...

**Comment by skranz** [comment]
Done
